In [2]:
import pandas as pd

In [ ]:
# pandas has two core object series, dataframe

In [8]:
# series
pd.Series((1,2,2,3),name="Age")

0    1
1    2
2    2
3    3
Name: Age, dtype: int64

In [11]:
# dataframe 
# dict 
di={"Name":["anand","mango","pen","mobile"],
    "Identity":["human","fruit","object",None]
}

df=pd.DataFrame(di)

In [13]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [15]:
df.head(2)

    Name Identity
0  anand    human
1  mango    fruit

In [16]:
df.tail(2)

     Name Identity
2     pen   object
3  mobile     None

In [37]:
df.sample()

  Name Identity
2  pen   object

In [38]:
df.head()

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     None

In [40]:
type(df["Name"])

pandas.core.series.Series

In [42]:
df[["Name","Identity"]]

     Name Identity
0   anand    human
1   mango    fruit
2     pen   object
3  mobile     None

In [44]:
count=[1,10,3,2]
df.insert(0,"count",count)

In [45]:
df

   count    Name Identity
0      1   anand    human
1     10   mango    fruit
2      3     pen   object
3      2  mobile     None

In [46]:
colour = "skin","orange","blue","black"

In [47]:
df["color"] =colour

In [49]:
df["id"] =[1,2,3,4]

In [62]:
df.sample()

   count   Name Identity   color  id
1     10  mango    fruit  orange   2

In [72]:
# new df df2 id, weight
df2 = pd.DataFrame({
    'id': [1, 2, 6, 4,5],
    'weight': [55, 62, 48, 70,None]
})

print(df2)

   id  weight
0   1    55.0
1   2    62.0
2   6    48.0
3   4    70.0
4   5     NaN

In [78]:
# merge or join
pd.merge(df,df2, how="left",on="id")

   count    Name Identity   color  id  weight
0      1   anand    human    skin   1    55.0
1     10   mango    fruit  orange   2    62.0
2      3     pen   object    blue   3     NaN
3      2  mobile     None   black   4    70.0

In [ ]:
pd.merge(df,df2, how=)  # sets